### ISSUE TITLE
Facebook test gets stuck adding post

### ISSUE THREAD

**Issue by bhackett1024** [replayio/playwright-tests#15]
The facebook fuzzing test almost always gets stuck when trying to add a post.  It either doesn't type anything into the new post box, or it doesn't click on the "post" button afterwards.  Examples:

https://replay.io/view?id=936f06b8-923c-4a3a-9635-12be994b10f6
https://replay.io/view?id=2d6d6669-322e-434a-b022-c223911fee0b

**Comment by gideonred** [comment]
This ticket has been moved to [BAC-1689](https://linear.app/replay/issue/BAC-1689/facebook-test-gets-stuck-adding-post)
