### ISSUE TITLE
Youtube test

### ISSUE THREAD

**Issue by jasonLaster** [replayio/playwright-tests#20]
When I click on a video in youtube with the cli, then skip ad does not skip the ad.

**Comment by jasonLaster** [comment]
Lets make a test that goes to youtube.com and clicks on a video. We don't need to test "skip ad"

**Comment by ryanjduffy** [comment]
Mistakenly tagged this in #64 so reopening

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-162](https://linear.app/replay/issue/RUN-162/youtube-test)
