### ISSUE TITLE
Record tiptap

### ISSUE THREAD

**Issue by jasonLaster** [replayio/playwright-tests#24]
https://tiptap.dev/

[Example Video](https://www.loom.com/share/9fc2b36301a7488db42d4fdbc884a43f)

### Plan
1. go to https://tiptap.dev/examples/default
2. select React tab
3. select text and click on the commands like bold, ...
4. edit the text in the editor e.g. add bullets, code blocks, ...

**Comment by gideonred** [comment]
This ticket has been moved to [BAC-1695](https://linear.app/replay/issue/BAC-1695/record-tiptap)
