### ISSUE TITLE
add finviz

### ISSUE THREAD

**Issue by jasonLaster** [replayio/playwright-tests#28]
https://finviz.com/

[Example video](https://www.loom.com/share/67f13891b2014814a058be5f51e74f2f)

### Plan
1. go to https://finviz.com/
2. click maps link in the header
3. click one of the boxes in the heat map
4. click bubbles link in the left
5. mouse over some circles

**Comment by gideonred** [comment]
This ticket has been moved to [BAC-1697](https://linear.app/replay/issue/BAC-1697/add-finviz)
