### ISSUE TITLE
Record replit

### ISSUE THREAD

**Issue by jasonLaster** [replayio/playwright-tests#39]
It should be easy to write a test that goes to a simple replit and views the code / output. 

We might be able to do more if we copy their selenium test
https://replit.com/@sergeichestakov/selenium

**Comment by ryanjduffy** [comment]
I landed https://github.com/RecordReplay/playwright-tests/pull/38 today. Lemme know if there are other scenarios you'd like to include and i'll update the example.

**Comment by gideonred** [comment]
This ticket has been moved to [BAC-1698](https://linear.app/replay/issue/BAC-1698/record-replit)
